import { defineConfig, devices } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(currentDir, '../..');

/**
 * E2E 隔离约定（HANDOFF §11.1 / §14.3）：
 * - 本机可能有常驻正式后端（LaunchAgent uvicorn）占用 8000 端口，且真实 `.env`
 *   会启用盘前/回填调度器。E2E 后端因此使用独立端口 + 独立 ENV_FILE + 独立
 *   SQLite 文件，保证对真实 `data/stock_analysis.db` 与 `.env` 零读零写。
 * - `src/config.py` 与 `src/auth.py` 都遵循 `ENV_FILE`，所以指向下面生成的
 *   e2e.env 后，真实 `.env` 完全不会被加载（包括 `_get_env_file_value` 的
 *   “.env 文件优先” runtime keys）。
 * - 每次运行前删除 e2e DB（含 -wal/-shm），让 schema 初始化在空库上执行。
 */
const E2E_BACKEND_PORT = 8765;
const artifactsDir = path.join(currentDir, 'e2e', '.artifacts');
const e2eDatabasePath = path.join(artifactsDir, 'e2e-stock-analysis.db');
const e2eEnvFilePath = path.join(artifactsDir, 'e2e.env');

const e2eEnvOverrides: Record<string, string> = {
  DATABASE_PATH: e2eDatabasePath,
  ADMIN_AUTH_ENABLED: 'false',
  MOOMOO_OPEND_ENABLED: 'false',
  MOOMOO_JOURNAL_REFRESH_ENABLED: 'false',
  MOOMOO_PREMARKET_PREFETCH_ENABLED: 'false',
  PREMARKET_RESEARCH_SCHEDULER_ENABLED: 'false',
  OPPORTUNITY_OUTCOME_SCHEDULER_ENABLED: 'false',
  SCHEDULE_ENABLED: 'false',
  MARKET_REVIEW_ENABLED: 'false',
  WEBUI_AUTO_BUILD: 'false',
  BOT_ENABLED: 'false',
};

fs.mkdirSync(artifactsDir, { recursive: true });
for (const suffix of ['', '-wal', '-shm']) {
  fs.rmSync(`${e2eDatabasePath}${suffix}`, { force: true });
}
fs.writeFileSync(
  e2eEnvFilePath,
  [
    '# Generated by playwright.config.ts on every E2E run. Do not edit.',
    '# Isolated backend env: throwaway SQLite DB, all schedulers/providers off, auth off.',
    ...Object.entries(e2eEnvOverrides).map(([key, value]) => `${key}=${value}`),
    '',
  ].join('\n'),
);

function resolveBackendCommand() {
  if (process.env.DSA_WEB_SMOKE_BACKEND_CMD) {
    return process.env.DSA_WEB_SMOKE_BACKEND_CMD;
  }

  const serveArgs = `main.py --webui-only --host 127.0.0.1 --port ${E2E_BACKEND_PORT}`;

  const unixVenvPython = path.join(repoRoot, '.venv', 'bin', 'python');
  if (fs.existsSync(unixVenvPython)) {
    return `${unixVenvPython} ${serveArgs}`;
  }

  const windowsVenvPython = path.join(repoRoot, '.venv', 'Scripts', 'python.exe');
  if (fs.existsSync(windowsVenvPython)) {
    return `"${windowsVenvPython}" ${serveArgs}`;
  }

  // 无 .venv 时优先 python3（macOS/Linux 通常没有 `python` alias）。
  return `${process.platform === 'win32' ? 'python' : 'python3'} ${serveArgs}`;
}

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false,
  retries: process.env.CI ? 2 : 0,
  reporter: 'list',
  use: {
    baseURL: 'http://127.0.0.1:4173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  webServer: [
    {
      command: resolveBackendCommand(),
      cwd: repoRoot,
      env: {
        // ENV_FILE 使真实 .env 不被加载；其余键再显式覆盖一遍，双保险。
        ENV_FILE: e2eEnvFilePath,
        ...e2eEnvOverrides,
      },
      url: `http://127.0.0.1:${E2E_BACKEND_PORT}/api/v1/auth/status`,
      // 绝不复用已在运行的后端：本机常驻正式后端使用真实 .env 与真实 DB。
      reuseExistingServer: false,
      timeout: 120_000,
    },
    {
      command: 'npm run dev -- --host 127.0.0.1 --port 4173 --strictPort',
      cwd: currentDir,
      env: {
        DSA_WEB_API_PROXY_TARGET: `http://127.0.0.1:${E2E_BACKEND_PORT}`,
      },
      url: 'http://127.0.0.1:4173',
      reuseExistingServer: false,
      timeout: 120_000,
    },
  ],
  projects: [
    {
      name: 'chromium',
      // channel: 'chrome' 使用本机已安装的 Google Chrome，避免依赖
      // `npx playwright install` 下载与当前 @playwright/test 版本匹配的
      // bundled chromium（本机缓存与 1.58.2 所需版本不一致）。
      use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    },
  ],
});
