import { vi } from 'vitest';
import type { PositionEpisodeController } from '../PositionEpisodesPanel';
import type {
  CanonicalEpisodeBuildPlanResponse,
  EpisodeBuildActivationResponse,
  EpisodeBuildActivationState,
  EpisodeBuildResponse,
  PositionEpisodeDetailResponse,
  PositionEpisodeItem,
  PositionEpisodeListResponse,
} from '../../../types/journal';

export const openAggregateEpisode: PositionEpisodeItem = {
  id: 41,
  episodeBuildId: 7,
  strategyEpisodeId: 17,
  episodeKey: 'position-41',
  lineageKey: 'lineage-41',
  strategyType: 'single_contract',
  instrument: {
    rawSymbol: 'NVDA260619C00150000',
    assetType: 'option',
    underlying: 'NVDA',
    expiry: '2026-06-19',
    strike: '150.0000000000',
    optionRight: 'C',
    contractMultiplier: '100.0000000000',
    currency: 'USD',
  },
  direction: 'long',
  lifecycleStatus: 'open',
  openedAt: '2026-06-20T14:31:00Z',
  closedAt: null,
  holdSeconds: null,
  openedQuantity: '3.0000000000',
  closedQuantity: '1.0000000000',
  remainingQuantity: '2.0000000000',
  averageEntryPrice: '2.5000000000',
  averageExitPrice: null,
  realizedPnlGross: null,
  totalFee: '0.2500000000',
  realizedPnlNet: null,
  reviewStatus: 'in_progress',
  reviewRevision: 2,
  reviewUpdatedAt: '2026-07-22T09:30:00Z',
  quality: {
    completenessStatus: 'partial',
    completenessScore: '0.8000',
    constructionBasis: 'aggregate_orders',
    contractMultiplierBasis: 'occ',
    openingBoundaryPolicy: 'assumed_flat_unverified',
    assumedFlatUnverified: true,
    leftBoundaryVerified: false,
    isLeftCensored: true,
    isRightCensored: true,
    pnlSummaryEligible: false,
    groupFeeUnallocated: false,
    pnlExclusionReasons: ['boundary_unverified', 'open'],
  },
};

export const closedEpisode: PositionEpisodeItem = {
  ...openAggregateEpisode,
  id: 42,
  episodeKey: 'position-42',
  instrument: { ...openAggregateEpisode.instrument, rawSymbol: 'TSLA260619P00200000', underlying: 'TSLA' },
  lifecycleStatus: 'closed',
  closedAt: '2026-06-21T15:31:00Z',
  holdSeconds: 90000,
  openedQuantity: '1.0000000000',
  closedQuantity: '1.0000000000',
  remainingQuantity: '0.0000000000',
  realizedPnlGross: '125.0000000000',
  totalFee: '1.2500000000',
  realizedPnlNet: '123.7500000000',
  reviewStatus: 'completed',
  reviewRevision: 3,
  reviewUpdatedAt: '2026-07-22T10:00:00Z',
  quality: {
    ...openAggregateEpisode.quality,
    constructionBasis: 'fills',
    isRightCensored: false,
    pnlExclusionReasons: ['boundary_unverified', 'assumed_flat_unverified'],
  },
};

export const readyList: PositionEpisodeListResponse = {
  dataState: 'ready',
  build: {
    id: 7,
    buildKey: 'build-7',
    builderName: 'position_episode_builder',
    builderVersion: '1.1.0',
    status: 'succeeded',
    sourceBatchIds: [2],
    sourceKind: 'csv_batch',
    sourceWindowStart: '2026-03-04T00:00:00Z',
    sourceCutoffAt: '2026-07-19T23:59:59Z',
    positionEpisodeCount: 2,
    unresolvedEvidenceCount: 0,
    completenessScore: '0.8000',
    openingBoundaryPolicy: 'assumed_flat_unverified',
    assumedFlatUnverified: true,
    executionGroupCount: 0,
    groupFeeAffectedEpisodeCount: 0,
    retainedExecutionGroupFeeTotal: '0.0000000000',
    feeConservationByCurrency: {},
    legFeeAttributionComplete: true,
    partialReasons: ['opening_boundary_unverified'],
    recordedAt: '2026-07-21T10:00:00Z',
  },
  reconciliation: {
    status: 'passed',
    scope: 'partial_window',
    partialWindow: true,
    windowStart: '2026-06-19T23:59:59Z',
    windowEnd: '2026-07-19T23:59:59Z',
    matchedOrderCount: 1089,
    totalOrderCount: 3542,
  },
  summary: {
    totalEpisodeCount: 2,
    openEpisodeCount: 1,
    closedEpisodeCount: 1,
    boundaryUnverifiedEpisodeCount: 2,
    leftCensoredEpisodeCount: 1,
    incompleteEpisodeCount: 1,
    aggregateOnlyEpisodeCount: 1,
    groupFeeAffectedEpisodeCount: 0,
    headlinePnl: {
      eligibleClosedCount: 0,
      excludedEpisodeCount: 2,
      eligibilityRule: 'strict',
      exclusionCounts: { boundary_unverified: 2 },
      realizedPnlGross: null,
      totalFee: null,
      realizedPnlNet: null,
    },
    conditionalPnl: {
      basis: 'closed_known_cash_flows_under_opening_boundary_policy',
      openingBoundaryPolicy: 'assumed_flat_unverified',
      count: 1,
      realizedPnlGross: '125.0000000000',
      totalFee: '1.2500000000',
      realizedPnlNet: '123.7500000000',
      includedInHeadline: false,
    },
  },
  total: 2,
  page: 1,
  perPage: 50,
  reviewQueue: {
    pending: 4,
    inProgress: 1,
    completed: 5,
    total: 10,
  },
  items: [openAggregateEpisode, closedEpisode],
};

export const canonicalPreview: CanonicalEpisodeBuildPlanResponse = {
  dataState: 'ready',
  canonicalSetId: 1,
  canonicalSetSha256: 'a'.repeat(64),
  buildKey: 'b'.repeat(64),
  sourceBatchIds: [2, 3],
  sourceWindowStart: '2026-01-01T00:00:00Z',
  sourceWindowEnd: '2026-07-19T23:59:59Z',
  sourceEventCount: 5974,
  aggregateOrderEventCount: 574,
  detailedFillEventCount: 5400,
  plannedPositionEpisodeCount: 1441,
  plannedOpenEpisodeCount: 4,
  plannedClosedEpisodeCount: 1437,
  sourceKnownFeeTotal: '151750.7500000000',
  allocatedKnownFeeTotal: '151750.7500000000',
  retainedExecutionGroupFeeTotal: '0.0000000000',
  feeConservationByCurrency: {
    USD: {
      ordinarySource: '151750.7500000000',
      ordinaryAllocated: '151750.7500000000',
      retainedExecutionGroup: '0.0000000000',
      sourceKnown: '151750.7500000000',
      accounted: '151750.7500000000',
    },
  },
  feeConserved: true,
  executionGroupCount: 0,
  groupFeeAffectedEpisodeCount: 0,
  legFeeAttributionComplete: true,
  openingBoundaryPolicy: 'assumed_flat_unverified',
  requiresAssumedFlatAcceptance: true,
  requiresGroupFeeScopeAcceptance: false,
  defaultBuildId: 7,
  defaultPositionEpisodeCount: 1439,
  episodeCountDelta: 2,
  defaultWillChange: false,
  confirmAllowed: true,
  warnings: [],
};

export const canonicalBuildResult: EpisodeBuildResponse = {
  dataState: 'ready',
  duplicate: false,
  build: {
    ...readyList.build!,
    id: 9,
    buildKey: canonicalPreview.buildKey!,
    sourceBatchIds: [2, 3],
    sourceKind: 'canonical_set',
    canonicalSetId: 1,
    canonicalSetSha256: canonicalPreview.canonicalSetSha256,
    positionEpisodeCount: 1441,
  },
  reconciliation: readyList.reconciliation!,
  // A canonical build has no snapshot-inherited openings, so its report
  // never counts left-censored episodes.
  summary: { ...readyList.summary!, leftCensoredEpisodeCount: 0 },
  message: 'canonical episode build appended',
};

export const activationState: EpisodeBuildActivationState = {
  accountKey: 'default_moomoo_us',
  selectionSource: 'csv_fallback',
  currentActivationId: null,
  currentActivationSequence: null,
  currentBuildId: 7,
  currentBuildKey: 'c'.repeat(64),
  canonicalSetId: null,
  canonicalSetSha256: null,
  previousActivationId: null,
  previousBuildId: null,
  activatedAt: null,
};

export const activationResponse: EpisodeBuildActivationResponse = {
  activationId: 12,
  activationKey: 'd'.repeat(64),
  duplicate: false,
  state: {
    ...activationState,
    selectionSource: 'activation',
    currentActivationId: 12,
    currentActivationSequence: 1,
    currentBuildId: 9,
    currentBuildKey: canonicalBuildResult.build.buildKey,
    canonicalSetId: 1,
    canonicalSetSha256: canonicalPreview.canonicalSetSha256,
    previousBuildId: 7,
    activatedAt: '2026-07-30T14:00:00Z',
  },
  message: 'canonical Episode build 9 activated',
  tradingActionPerformed: false,
};

export const episodeDetail: PositionEpisodeDetailResponse = {
  dataState: 'ready',
  build: readyList.build!,
  reconciliation: readyList.reconciliation!,
  item: openAggregateEpisode,
  matching: { method: 'signed_position_zero_crossing' },
  evidenceSummary: { allocationCount: 1 },
  completeness: { leftBoundaryVerified: false },
  provenance: { builderVersion: '1.1.0' },
  evidence: [{
    id: 61,
    evidenceKey: 'order-observation-61',
    evidenceKind: 'order',
    eventRole: 'open',
    allocationSequence: 0,
    evidenceTime: '2026-06-20T14:31:00Z',
    allocatedQuantity: '1.0000000000',
    allocatedFee: '0.2500000000',
    allocatedCashFlow: '-250.0000000000',
    allocationRatio: '1.0000000000',
    brokerOrderObservationId: 101,
    brokerFillObservationId: null,
    allocation: { timingPrecision: 'order_time_proxy' },
    provenance: { syntheticFill: false },
  }],
};

export function makeController(
  overrides: Record<string, unknown> = {},
): PositionEpisodeController {
  return {
    list: readyList,
    loading: false,
    error: null,
    reload: vi.fn(),
    detailById: {},
    detailLoadingId: null,
    detailError: null,
    loadDetail: vi.fn().mockResolvedValue(undefined),
    building: false,
    buildResult: null,
    buildAssumedFlat: vi.fn().mockResolvedValue(undefined),
    canonicalPreview,
    canonicalPreviewLoading: false,
    canonicalPreviewError: null,
    reloadCanonicalPreview: vi.fn(),
    canonicalBuilding: false,
    canonicalBuildResult: null,
    buildCanonical: vi.fn().mockResolvedValue(canonicalBuildResult),
    ...overrides,
  } as PositionEpisodeController;
}
